### ISSUE TITLE
JsonPath使用getString方法求值，当匹配不到时，无法获取null值

### ISSUE THREAD

**Issue by itachy-zhu** [noear/snack3#19]
举个栗子：
当我有个json：{"A": {"B": 1}}
当我load(json, new Options(0)).select("$.A.B1").getString()    

查询出来的结果一直是“”，而不是null ，尽管我额外设置了Options【后面这个Options被忽略掉了】，跟踪下来看到：

    /**
     * 执行jpath指令
     */
    private static ONode exec(JsonPath jsonPath, ONode source, boolean useStandard) {
        ONode tmp = source;
        boolean branch_do = false;
        for (Segment s : jsonPath.segments) {
            if (tmp == null) {//多次转换后，可能为null
                break;
            }

            if (branch_do && (useStandard || s.cmdAry != null)) { //..a[x] 下属进行分支处理 //s.cmdAry != null
                ONode tmp2 = new ONode().asArray();

                Consumer<ONode> act1 = (n1) -> {
                    ONode n2 = s.handler.run(s, source, n1, useStandard);
                    if (n2 != null) {
                        if (s.cmdAry != null) {
                            if (n2.isArray()) {
                                tmp2.addAll(n2.ary());
                            } else {
                                tmp2.addNode(n2);
                            }
                        } else {
                            tmp2.addNode(n2);
                        }
                    }
                };

                tmp.ary().forEach(act1);

                tmp = tmp2;

                if (useStandard == false) {
                    branch_do = false;
                }
            } else {
                tmp = s.handler.run(s, source, tmp, useStandard);
                branch_do = s.cmdHasUnline;
            }
        }

        if (tmp == null) {
            return new ONode();        //   问题在这里，为什么要忽略设置Options而使用默认构造的？
        } else {
            return tmp;
        }
    }

想问下，这里在new ONode时可否将“ONode source” 的options设置到新ONode中，而非使用默认的，因为我这里就是不想使用使用Feature.StringNullAsEmpty。

**Comment by noear** [comment]
谢谢反馈。马上处理：）

**Comment by noear** [comment]
v3.2.30 已发布。。。过会儿，就可以使用了。

**Comment by itachy-zhu** [comment]
暂哈。。
