### ISSUE TITLE
对于某个ONode要怎么获取它的key

### ISSUE THREAD

**Issue by mshen6666** [noear/snack3#20]
我现在有一个场景是需要先将值取出来，然后把它转换成我需要的，再放在之前的json位置中，如果用jsonPath就可以用DocumentContext，然后通过jsonPath直接set值，但是用ONode我发现，在set的时候，我需要用到key值。所以在这个时候我要怎么获取到这个node的key值，或者这个问题有更好的解决方案吗。感谢！
` //先将要改动的拿出来，然后把值改为空，把后来改完的node加进去，最后进行一轮判空输出
                    ONode o = ONode.loadStr(json);
                    ONode childNode = o.select(jsonPath);
                    String bizValue = o.select(jsonPath).getString();
                    //将原来的值改为空
                    o.select(jsonPath).asNull();
                    //操作原来的值做转换，拿到操作完的值
                    String convertResult = operateData(ruleCode, mappingCode, bizValue);
                    childNode.val(convertResult);
                    //最后怎么将o中的这个节点的值替换掉`

**Comment by noear** [comment]
snack3 可以在 jsonpath 查询后直接改值的：

```java
ONode o = ONode.loadStr(json); 
o.select(jsonPath).val("1");
```

另外，你取出值改掉，即已经改掉了：
```java
ONode o = ONode.loadStr(json); 
oNode o1 = o.select(jsonPath);

o1.val("1");//此时，o 里的对应节点就已经改掉了。。。因为o1 是o里的一个节点
```

**Comment by mshen6666** [comment]
哦哦，我明白了。如果我对应的jsonpath是一个数组，那也就是遍历数组然后给对应的节点val就可以了对吗

**Comment by mshen6666** [comment]
好的，谢谢！
