### ISSUE TITLE
数组类型字段获取需求

### ISSUE THREAD

**Issue by zuohl** [noear/snack3#22]
ONode.getOrNew(String key)
当key包含数组下标时,会无法正确解析,比如a[0]

**Comment by zuohl** [comment]
不知道我这个表述够不够清晰

**Comment by noear** [comment]
麻烦你写个简单的小 demo 看下

**Comment by zuohl** [comment]
> 麻烦你写个简单的小 demo 看下

https://gitee.com/noear/snack3/issues/I603BJ 应该跟这个同学一样的需求,目前只能通过ONode.getOrNew折衷实现,用这个实现就得对key做类似于select里jsonpath的解析

**Comment by zuohl** [comment]
目前我的做法是一层path一层path的遍历,做一些基本的jsonpath语法支持

**Comment by zuohl** [comment]
应该算需求,,是我描述问题

**Comment by zuohl** [comment]
> 不支持根据 jsonpath 生成 ONode。。。不过有 o.getOrNew(idx) 的接口，用于获取或创建 array 的 item

这个我知道,但是如果是复杂的就得自己做支持类似于jsonpath的语法解析了,这个就是我们目前的做法,但是觉得不太优雅
比如$.store.book[0].title,如果我想修改这个title,我就得针对这个$.store.book[0].title做三层遍历,遇到book[0]这样的我还得去解析,简单的还行,遇到复杂的就歇菜了

**Comment by zuohl** [comment]
而且层层解析还有个问题就是因为getOrNew不支持返回array类型,用 o.getOrNew(idx)去获取这里就会存在多次的对象和数组互相转换

**Comment by zuohl** [comment]
我需要的其实就是一个   
` public ONode setNode(String key, String jpath) {

    }
`

**Comment by noear** [comment]
这个需求，确实有人提过。。。容我想想！

**Comment by zuohl** [comment]
> 这个需求，确实有人提过。。。容我想想！

好,那我们就暂不继续挖坑了.等你好消息

**Comment by zuohl** [comment]
> 3.2.57 新加了个接口 selectOrNew：
> 
> ```java
> public class JsonPathNewTest {
>     @Test
>     public  void test1(){
>         ONode oNode = new ONode();
>         oNode.selectOrNew("$.orders[0].price").val(500);
>         System.out.println(oNode.toJson());
>         //{"orders":[{"price":500}]}
> 
>         assert "{\"orders\":[{\"price\":500}]}".equals(oNode.toJson());
> 
> 
>         oNode.selectOrNew("$.orders[10].price").val(600);
>         System.out.println(oNode.toJson());
>         //{"orders":[{"price":500},null,null,null,null,null,null,null,null,null,{"price":600}]}
> 
>         oNode.select("$.orders").forEach(n->n.asObject());
>         System.out.println(oNode.toJson());
>         //{"orders":[{"price":500},{},{},{},{},{},{},{},{},{},{"price":600}]}
>     }
> }
> ```

大佬666
