### ISSUE TITLE
能支持更多function吗

### ISSUE THREAD

**Issue by thiner** [noear/snack3#26]
相比JsonPath，这个库少了很多好用的function，比如length(), concat(), index()等等。

**Comment by noear** [comment]
可以写几个使用的小demo看看吗？

**Comment by thiner** [comment]
这里有个JsonPath的在线版evaluator。我试了一下，效果一言难尽。
- `$.store.book[0].keys()`: 返回了object keys
- `$..title.concat(",")`: 返回了_"Sayings of the CenturySword of HonourMoby DickThe Lord of the Rings"_很显然没有正确添加“，”分隔符。

**Comment by noear** [comment]
下版增加：size(), length(), keys() 函数。。。有参数的函数，暂时不支持。如果还有别的函数提议，可以一并提了：）

**Comment by noear** [comment]
其实这几个函数意义不大。。。不像 min() 确实带来方便
