### ISSUE TITLE
JsonPath中的function会支持吗

### ISSUE THREAD

**Issue by Heemooo** [noear/snack3#30]
![image](https://github.com/noear/snack3/assets/22309030/0f3761d2-942e-43c5-a3ce-446f42819136)
试用了一下，感觉很不错，希望可以支持concat函数

**Comment by noear** [comment]
必要的支持函数，都在 readme 上可见的：）

**Comment by Heemooo** [comment]
concat 也很必要啊 😂，我们相当需要，不行还是得整原版了

**Comment by noear** [comment]
你可以提交个 pr 试试：）
