### ISSUE TITLE
ONode 如何判断构建失败?

### ISSUE THREAD

**Issue by shaoerkuai** [noear/snack3#31]
![image](https://github.com/noear/snack3/assets/117460332/3ccb1ec4-ad4f-4e9d-9e34-14e396c7425d)

jackson是通过JsonProcessingException异常来判断序列化失败的，但是这里提到ONode返回一个空，是返回null还是？
没有看到isEmpty的相关函数呢，不知道该如何判断构建失败。

**Comment by noear** [comment]
@shaoerkuai 赞！
