### ISSUE TITLE
jsonpath 问题

### ISSUE THREAD

**Issue by dxfeng10** [noear/snack3#4]
['<name>' (, '<name>')] | 表示一个或多个子节点

ONode n = ONode.load("{code:1,msg:'Hello world!',data:[{a:'b',c:'d'}]}");

这种写法可以正常获取到值
System.out.println(n.select("$.data[*].a"));

以下两种写法获取不到值
System.out.println(n.select("$.data[*]['a']"));
System.out.println(n.select("$.data[*]['a','c']"));

**Comment by noear** [comment]
System.out.println(n.select("$.data[*]['a']"));
System.out.println(n.select("$.data[*]['a','c']"));

试一下：）

**Comment by noear** [comment]
谢谢反馈，我尽快处理一下：）

**Comment by noear** [comment]
之前，一直在担心，这种写汉有没有问题："$.data[\*]['a','c']"

我暂时把它加上支持了。。。后面再认真研究一下语法说明。。。看看是不是合规的
