### ISSUE TITLE
[3.1.5.9] 根据jsonpath更新json串

### ISSUE THREAD

**Issue by will86** [noear/snack3#6]
您好，作者。
我正在使用`3.1.5.9`版本的`snack3`，现有这样的需求，通过传入参数的jsonpath，定位到json指定的位置，然后对该指定路径的json值进行修改。

之前使用的`
com.jayway.jsonpath.JsonPath`，是这样实现的

`        // JsonPath的配置信息
        Configuration conf = Configuration.defaultConfiguration().addOptions(Option.DEFAULT_PATH_LEAF_TO_NULL, Option.SUPPRESS_EXCEPTIONS);

        // 指定配置信息，获取json上下文对象
        DocumentContext context = JsonPath.using(conf).parse(rawJsonStr);

        // 预编译JsonPath
        JsonPath path = JsonPath.compile(jsonPathStr);

        // 在指定的path节点上，设置新值
        try {
            context.set(path, newValue);
        }
        // 路径找不到时，抛出异常
        catch (PathNotFoundException e) {
            throw new RuntimeException("JasonPath:" + jsonPathStr + " not found.", e);
        }

        // 获取新的json字符串
        String newJsonStr = context.jsonString();
`

但因为`com.jayway.jsonpath.JsonPath`的性能问题，想将类库替换为snack3，想麻烦大佬看看snack3下，如何实现上述需求。

**Comment by noear** [comment]
谢谢你的关注。。。可否加到QQ群里交流：22200020

方便更快速的交流。


另外，目前最新版本号为：3.1.8 可以升级一下：）



关于Json path 的查询结果，只能争对叶子的修改是有效的。。。因为在查询构建中，会重新构建树干。

例:

o.select(“xxx.xxx.xxx.user”).foreach(n->{ n.get(“icon”).val(“xxxxxx") }); //这时性的修改，对根节点有效…因为 icon 是叶子上的值

然后 o.toJson();

**Comment by noear** [comment]
谢谢你的关注。。。可否加到QQ群里交流：22200020

方便更快速的交流。


另外，目前最新版本号为：3.1.8 可以升级一下：）


关于Json path 的查询结果，只能争对叶子的修改是有效的。。。因为在查询构建中，会重新构建树干。

例:

o.select(“xxx.xxx.xxx.user”).foreach(n->{ n.get(“icon”).val(“xxxxxx") }); //这时性的修改，对根节点有效…因为 icon 是叶子上的值

然后 o.toJson();

**Comment by noear** [comment]
完整代码是：
```java
ONode n = ONode.loadStr("{...}");
n.select("$.xx.xx.user").for(n -> n.get("icon").val("xxxxx"));

String new_json = n.toJson();

```
