### ISSUE TITLE
请问如何对数组中的Json来动态的替换，并且保证数组的顺序和里面的值不乱

### ISSUE THREAD

**Issue by AtticusLv** [noear/snack3#8]
如题
{
	"a":[
		{
			"b":1,
			"c":2
		},
		{
			"b":11,
			"c":12
		}
	]
},
想映射成为下面的数组

{
	"saa": [
		{
			"sb":1,
			"sc":2
		},
		{
			"sb":11,
			"sc":12
		}
	]
}

**Comment by noear** [comment]
谢谢反馈，麻烦下次到gitee。。。因为 github 有时候打不开，所以不怎么来：）

**Comment by noear** [comment]
你这个问题对 snack 来说非常简单，它有个 rename 接口。

```java
ONode node = ONode.loadStr(json);
node.rename("a","saa");
```
